#define _GNU_SOURCE
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define FONT_EMPTY_CHAR '.'
#define FONT_SITE_CHAR '*'
#define START_CHAR "char "

int fontStr2Int(char* str);
FILE* openFile(char* name, char* type);

int main(int argc, char* argv[]) {
    char* txt = argv[1];
    char* out = argv[2];
    printf("in: %s. out %s \n", txt, out);

    FILE* inFile = openFile(txt, "r");
    FILE* outFile = openFile(out, "w");
    size_t len = 128;
    char line[len];
    char* read;

    fprintf(outFile, "// generated by convHankakuTxt\n\n");
    // fprintf(outFile, "int main(){\n");
    fprintf(outFile, "// 0x100 * 16\n");
    fprintf(outFile, "static char hankaku[0x100][16]={\n");

    while ((read = fgets(line, len, inFile)) != NULL) {
        // printf("ssss %d\n",strlen(START_CHAR));
        // printf("cccc %d\n",strncmp(line, START_CHAR, strlen(START_CHAR))    );
        if (strncmp(line, START_CHAR, strlen(START_CHAR)) == 0) {
            // start parse new font
            fprintf(outFile, "\t// %.4s \n\t", line + strlen(START_CHAR));
            fprintf(outFile, "{ ");
            for (int i = 0;i < 16;i++) {
                fgets(line, len, inFile);
                int dot = fontStr2Int(line);
                if (i == 8) {
                    fprintf(outFile, "\n\t");
                }
                fprintf(outFile, "0x%02x, ", dot);
            }
            fprintf(outFile, " }, \n\n");
        }
    }
    fprintf(outFile, "%s", "\n};");

    fclose(outFile);
    fclose(inFile);
}
int fontStr2Int(char* str) {
    int res = 0;
    for (int i = 0; i < 8; i++) {
        res <<= 1;
        if (str[i] == FONT_SITE_CHAR) {
            res |= 1;
        }
    }
    return res;
}

FILE* openFile(char* name, char* type) {
    FILE* file = fopen(name, type);
    if (file == NULL) {
        printf("no file found %s\n", name);
        exit(EXIT_FAILURE);
    }
    return file;
}

/*
    static char hankaku[128][16];
    static char hankaku[xxx] = {

    }
    static char font_A[16] = {
        0x00, 0x18, 0x18, 0x18, 0x18, 0x24, 0x24, 0x24,
        0x24, 0x7e, 0x42, 0x42, 0x42, 0xe7, 0x00, 0x00,
    };

 */